# Generated by Django 5.1.1 on 2024-10-08 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('first_diagnos', models.TextField()),
                ('start_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gender', models.CharField(choices=[('Mr', 'Мужчина'), ('Ms', 'Женщина')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
