# Generated by Django 5.1.1 on 2024-10-11 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient_profile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pacient_profile',
            name='registration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pacient_profile',
            name='gender',
            field=models.CharField(choices=[('Mr', 'Мужчина'), ('Ms', 'Женщина')], max_length=2),
        ),
    ]
