# Generated by Django 5.1.1 on 2024-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0003_diets_list_diseases_list_preparats_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='doc_stage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pacient_profile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
