# Generated by Django 5.1.1 on 2024-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0004_alter_doctor_profile_doc_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient_reports',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
