# Generated by Django 5.1.1 on 2024-10-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0005_pacient_reports_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient_reports',
            old_name='pacient_profile_id',
            new_name='pacient_profile',
        ),
    ]
