# Generated by Django 5.1.1 on 2024-10-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0006_rename_pacient_profile_id_pacient_reports_pacient_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient_reports',
            name='pacient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_control.pacient_profile'),
        ),
    ]
