# Generated by Django 5.1.1 on 2024-10-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0007_alter_pacient_reports_pacient_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='diets_id',
            new_name='diets',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='doctor_profile_id',
            new_name='doctor_profile',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='preparats_id',
            new_name='preparats',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
