# Generated by Django 5.1.1 on 2024-10-16 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0008_rename_diets_id_assignment_diets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='diets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weight_control.diets_list'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='doctor_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weight_control.doctor_profile'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='preparats',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weight_control.pacient_profile'),
        ),
        migrations.AlterField(
            model_name='doc_ratings',
            name='doctor_profile_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weight_control.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='doc_ratings',
            name='patient_profile_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weight_control.pacient_profile'),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='foto_file_path',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pacient_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='preparats',
            field=models.ManyToManyField(to='weight_control.preparats_list'),
        ),
    ]
