# Generated by Django 5.1.1 on 2024-10-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0009_alter_assignment_diets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='preparats',
            new_name='preparats_list',
        ),
    ]
