# Generated by Django 5.1.1 on 2024-10-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0012_doctor_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient_profile',
            name='doc_attached',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='weight_control.doctor_profile'),
        ),
    ]
