# Generated by Django 5.1.1 on 2024-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0013_pacient_profile_doc_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='pacient_profile',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], max_length=7),
        ),
    ]
