# Generated by Django 5.1.1 on 2024-10-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0014_alter_doctor_profile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user_profile',
            new_name='pacient_profile',
        ),
    ]
