# Generated by Django 5.1.1 on 2024-10-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0016_rename_doctor_profile_id_doc_ratings_doctor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='doctor_profile',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='pacient_profile',
        ),
    ]
