# Generated by Django 5.1.1 on 2024-10-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0018_assignment_doctor_profile_assignment_pacient_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='weight_control.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pacient_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='weight_control.pacient_profile'),
        ),
    ]
