# Generated by Django 5.1.1 on 2024-10-26 12:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('weight_control', '0019_alter_assignment_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient_reports',
            name='weight_today',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Accompanying_disease_pacients',
        ),
    ]
